# Gitlab CI pipeline - also includes publishing stage if
# we ever get there...
# https://www.agundy.com/2021/03/10/elixir-gitlab-ci.html

stages:
  - test

.elixir: &elixir
  image: elixir:1.13
  before_script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get --only $MIX_ENV

lint:elixir:
  extends: .elixir
  stage: test
  variables:
    MIX_ENV: test
  script:
    - mix compile --warnings-as-errors --force
    - mix format --check-formatted

test:elixir:
  extends: .elixir
  stage: test
  coverage: '/\d+.\d+\%\s+\|\s+Total/'
  variables:
    MIX_ENV: test
  script:
    - mix test --cover
  artifacts:
    paths:
      - _build/test/lib/off_broadway_splunk/test-junit-report.xml
    reports:
      junit: _build/test/lib/off_broadway_splunk/test-junit-report.xml
