stages:
  - test
  - docs

.elixir: &elixir
  image: elixir:1.13
  cache:
    - paths:
        - deps
  before_script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get --only $MIX_ENV

lint:elixir:
  extends: .elixir
  stage: test
  variables:
    MIX_ENV: test
  script:
    - mix compile --warnings-as-errors --force
    - mix format --check-formatted

test:elixir:
  extends: .elixir
  stage: test
  coverage: '/\d+.\d+\%\s+\|\s+Total/'
  variables:
    MIX_ENV: test
  script:
    - mix test --cover
  artifacts:
    paths:
      - _build/test/lib/off_broadway_splunk/test-junit-report.xml
    reports:
      junit: _build/test/lib/off_broadway_splunk/test-junit-report.xml

pages:
  extends: .elixir
  stage: docs
  variables:
    MIX_ENV: test
  script:
    - mix docs --output public
  artifacts:
    paths:
      - public
  only:
    - master
    - tags
