name: Test

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
      - ".gitignore"
  pull_request:
    branches: [main]
    paths-ignore:
      - "*.md"
      - ".gitignore"
  workflow_dispatch:

jobs:
  test:
    name: Elixir Tests
    permissions:
      actions: read
      contents: read
      pull-requests: write
    uses: intility/reusable-elixir/.github/workflows/elixir-test.yaml@bf5899eb8f897af6da47d33ac9836c700ce77219 # v3.2.0
    with:
      otp-version: "28.3"
      elixir-version: "1.19.4"
      dialyzer: true
      sobelow: false
