name: Test

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
      - ".gitignore"
  pull_request:
    branches: [main]
    paths-ignore:
      - "*.md"
      - ".gitignore"
  workflow_dispatch:

jobs:
  test:
    name: Elixir Tests
    permissions:
      actions: read
      contents: read
      pull-requests: write
    uses: intility/reusable-elixir/.github/workflows/elixir-test.yaml@e57a7d7c69468613e5f521103f596acab3cc5b33 # v3.1.0
    with:
      otp-version: "28.3"
      elixir-version: "1.19.4"
      dialyzer: true
      sobelow: false
